#!/usr/bin/env python3
"""Convert Uhhhhhh-style binary .anim files into Roblox ModuleScript source.

Usage:
  python tools/anim_to_base64_modules.py projects/YhwachAlmighty/Assets/Animations --out YhwachAnimData

Copy each generated .lua ModuleScript into a Folder named YhwachAnimData next to
YhwachUI.client, AlmightyController.client, AnimLib, and AccessoryConfig.
The ModuleScripts return { Base64 = "..." }; they do not modify the original files.
"""
from __future__ import annotations

import argparse
import base64
from pathlib import Path

DEFAULT_NAMES = {
    "AlmightyAwake.anim": "AlmightyAwake",
    "AlmightyAura.anim": "AlmightyAura",
    "AlmightySlash.anim": "AlmightySlash",
    "Auswählen.anim": "Auswahlen",
    "Blut Vene Anhaben.anim": "BlutVeneAnhaben",
    "Sklaverei .anim": "Sklaverei",
}
CHUNK_SIZE = 6000


def lua_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def make_module(encoded: str) -> str:
    chunks = [encoded[i:i + CHUNK_SIZE] for i in range(0, len(encoded), CHUNK_SIZE)]
    lines = [
        "-- Generated by tools/anim_to_base64_modules.py; preserve the bytes exactly.",
        "return {",
        "\tBase64 = table.concat({",
    ]
    lines.extend("\t\t" + lua_quote(chunk) + "," for chunk in chunks)
    lines.extend(["\t}),", "}"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source_dir", type=Path, help="Folder containing the original .anim files")
    parser.add_argument("--out", type=Path, default=Path("YhwachAnimData"), help="Output folder for ModuleScript source files")
    args = parser.parse_args()

    if not args.source_dir.is_dir():
        parser.error(f"source folder does not exist: {args.source_dir}")
    args.out.mkdir(parents=True, exist_ok=True)

    missing = []
    written = []
    for filename, module_name in DEFAULT_NAMES.items():
        source = args.source_dir / filename
        if not source.is_file():
            missing.append(filename)
            continue
        encoded = base64.b64encode(source.read_bytes()).decode("ascii")
        target = args.out / f"{module_name}.lua"
        target.write_text(make_module(encoded), encoding="utf-8", newline="\n")
        written.append((target, source.stat().st_size, len(encoded)))

    for target, raw_size, encoded_size in written:
        print(f"Created {target} ({raw_size:,} bytes -> {encoded_size:,} Base64 chars)")
    if missing:
        print("Missing source files:")
        for name in missing:
            print(f"  - {name}")
        return 1
    print(f"Done: generated {len(written)} ModuleScripts. Import each as a ModuleScript under YhwachAnimData.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
